sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image for node 6
- ./build.sh node 6 6
# build image for node7
- ./build.sh node 7 7
- ./build.sh node latest 7
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV MYSQL_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag hypriot/rpi-mysql hypriot/rpi-mysql:$TAG
    docker push hypriot/rpi-mysql:$TAG
    docker push hypriot/rpi-mysql
  fi

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push pipirate/node:6 
  - docker push pipirate/node:7
  - docker push pipirate/node:latest
